// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Mock

struct SimulationState
{
    float3 Position;
    float3 Scale;
};

RWStructuredBuffer<SimulationState> SimulationStateBuffer;

uniform int DISPATCH_NUM;
uniform int COUNT_PER_DIMENSION;

[numthreads(2,2,1)]
void Mock (uint3 id : SV_DispatchThreadID)
{
    uint ID = id.x + id.y * COUNT_PER_DIMENSION;
    SimulationStateBuffer[ID].Position = ID;
    SimulationStateBuffer[ID].Scale    = ID;
}
